import { Product, Category } from '../types';

export const CATEGORIES: Category[] = ['Grocery', 'Dairy', 'Fruits & Veggies', 'Snacks', 'Beverages', 'Personal Care', 'Household'];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Aashirvaad Shudh Chakki Atta',
    name_hi: 'आशीर्वाद शुद्ध चक्की आटा',
    name_gu: 'આશીર્વાદ શુદ્ધ ચક્કી લોટ',
    price: 445,
    mrp: 495,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1606149059549-6042addafc5a?auto=format&fit=crop&q=80&w=800',
    description: '100% whole wheat flour, perfect for soft rotis. No maida added.',
    description_hi: '100% साबुत गेहूं का आटा, नरम रोटियों के लिए एकदम सही। कोई मैदा नहीं मिलाया गया।',
    description_gu: '100% આખા ઘઉંનો લોટ, નરમ રોટલી માટે યોગ્ય. કોઈ મેંદો ઉમેરવામાં આવ્યો નથી.',
    color: '#d4a373',
    unit: '5 kg',
    unit_hi: '5 किग्रा',
    unit_gu: '5 કિલો'
  },
  {
    id: '2',
    name: 'Amul Taaza Homogenised Milk',
    name_hi: 'अमूल ताज़ा होमोजेनाइज़्ड दूध',
    name_gu: 'અમૂલ તાઝા હોમોજેનાઇઝ્ડ દૂધ',
    price: 68,
    mrp: 72,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-125581db2be1?auto=format&fit=crop&q=80&w=800',
    description: 'Fresh toned milk, long shelf life. Perfect for tea and coffee.',
    description_hi: 'ताजा टोंड दूध, लंबी शेल्फ लाइफ। चाय और कॉफी के लिए बेहतरीन।',
    description_gu: 'તાજું ટોન્ડ દૂધ, લાંબી શેલ્ફ લાઇફ. ચા અને કોફી માટે યોગ્ય.',
    color: '#ffffff',
    unit: '1 L',
    unit_hi: '1 लीटर',
    unit_gu: '1 લીટર'
  },
  {
    id: '3',
    name: 'Tata Salt - Vacuum Evaporated',
    name_hi: 'टाटा नमक - वैक्यूम इवेपोरेटेड',
    name_gu: 'ટાટા મીઠું - વેક્યૂમ ઇવેપોરેટેડ',
    price: 28,
    mrp: 30,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1626197031507-c17099753214?auto=format&fit=crop&q=80&w=800',
    description: 'Iodized salt, the taste of India. Desh ka Namak.',
    description_hi: 'आयोडीन युक्त नमक, भारत का स्वाद। देश का नमक।',
    description_gu: 'આયોડાઇઝ્ડ મીઠું, ભારતનો સ્વાદ. દેશનું મીઠું.',
    color: '#0ea5e9',
    unit: '1 kg',
    unit_hi: '1 किग्रा',
    unit_gu: '1 કિલો'
  },
  {
    id: '4',
    name: 'Haldiram\'s Nagpur Aloo Bhujia',
    name_hi: 'हल्दीराम नागपुर आलू भुजिया',
    name_gu: 'હલ્દીરામ નાગપુર આલૂ ભુજિયા',
    price: 95,
    mrp: 110,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&q=80&w=800',
    description: 'Crispy potato mint noodles. The ultimate Indian tea-time snack.',
    description_hi: 'कुरकुरा आलू पुदीना नूडल्स। बेहतरीन भारतीय चाय समय नाश्ता।',
    description_gu: 'ક્રિસ્પી બટાકાની ફુદીનાની સેવ. શ્રેષ્ઠ ભારતીય ચા સમયનો નાસ્તો.',
    color: '#facc15',
    unit: '200 g',
    unit_hi: '200 ग्राम',
    unit_gu: '200 ગ્રામ'
  },
  {
    id: '5',
    name: 'Fresh Alphonso Mangoes',
    name_hi: 'ताजे हापुस आम',
    name_gu: 'તાજા હાફૂસ કેરી',
    price: 599,
    mrp: 799,
    category: 'Fruits & Veggies',
    image: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=800',
    description: 'Ratnagiri Alphonso Mangoes, known for their rich aroma and sweetness.',
    description_hi: 'रत्नागिरी हापुस आम, अपनी समृद्ध सुगंध और मिठास के लिए जाने जाते हैं।',
    description_gu: 'રત્નાગિરી હાફૂસ કેરી, તેની સુગંધ અને મીઠાશ માટે જાણીતી છે.',
    color: '#fbbf24',
    unit: '1 box (6 units)',
    unit_hi: '1 पेटी (6 नग)',
    unit_gu: '1 બોક્સ (6 નંગ)'
  },
  {
    id: '6',
    name: 'Red Label Tea',
    name_hi: 'रेड लेबल चाय',
    name_gu: 'રેડ લેબલ ચા',
    price: 310,
    mrp: 340,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4586d52c?auto=format&fit=crop&q=80&w=800',
    description: 'High-quality blend of CTC tea with richness and strength.',
    description_hi: 'समृद्धता और शक्ति के साथ सीटीसी चाय का उच्च गुणवत्ता वाला मिश्रण।',
    description_gu: 'ભરપૂર સ્વાદ અને મજબૂતી સાથે CTC ચાનું ઉચ્ચ ગુણવત્તાનું મિશ્રણ.',
    color: '#ef4444',
    unit: '500 g',
    unit_hi: '500 ग्राम',
    unit_gu: '500 ગ્રામ'
  },
  {
    id: '7',
    name: 'Amul Pasteurised Butter',
    name_hi: 'अमूल पाश्चुरीकृत मक्खन',
    name_gu: 'અમૂલ પાશ્ચરાઇઝ્ડ માખણ',
    price: 255,
    mrp: 275,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800',
    description: 'Utterly Butterly Delicious! Iconic Indian butter.',
    description_hi: 'बेहद स्वादिष्ट! प्रतिष्ठित भारतीय मक्खन।',
    description_gu: 'ખરેખર સ્વાદિષ્ટ! પ્રખ્યાત ભારતીય માખણ.',
    color: '#fde047',
    unit: '500 g',
    unit_hi: '500 ग्राम',
    unit_gu: '500 ગ્રામ'
  },
  {
    id: '8',
    name: 'Dettol Liquid Handwash',
    price: 99,
    mrp: 125,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1520333789090-1afc82db536a?auto=format&fit=crop&q=80&w=800',
    description: 'Original germ protection handwash with pH balanced formula.',
    color: '#22c55e',
    unit: '200 ml'
  },
  {
    id: '9',
    name: 'Daawat Rozana Super Basmati Rice',
    price: 385,
    mrp: 450,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800',
    description: 'Aromatic long grain basmati rice, aged for perfection.',
    color: '#f5f5f4',
    unit: '5 kg'
  },
  {
    id: '10',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    price: 135,
    mrp: 165,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1620706122100-31677449221b?auto=format&fit=crop&q=80&w=800',
    description: 'Light and healthy cooking oil, rich in Vitamins A & D.',
    color: '#fbbf24',
    unit: '1 L'
  },
  {
    id: '11',
    name: 'Maggi 2-Minute Noodles',
    price: 156,
    mrp: 168,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=800',
    description: 'Your favorite masala noodles. 12-pack value bundle.',
    color: '#ef4444',
    unit: '840 g'
  },
  {
    id: '12',
    name: 'Fresh Red Onions',
    price: 45,
    mrp: 60,
    category: 'Fruits & Veggies',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=800',
    description: 'Farm-fresh pungency, essential for every Indian curry.',
    color: '#a855f7',
    unit: '1 kg'
  },
  {
    id: '13',
    name: 'New Potatoes (Aloo)',
    price: 32,
    mrp: 45,
    category: 'Fruits & Veggies',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f02ac10dd?auto=format&fit=crop&q=80&w=800',
    description: 'Versatile and fresh potatoes, directly from the farm.',
    color: '#d97706',
    unit: '1 kg'
  },
  {
    id: '14',
    name: 'ID Fresh Paneer',
    price: 95,
    mrp: 110,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?auto=format&fit=crop&q=80&w=800',
    description: 'Soft and creamy malai paneer, no preservatives.',
    color: '#ffffff',
    unit: '200 g'
  },
  {
    id: '15',
    name: 'Parle-G Gold Biscuits',
    price: 25,
    mrp: 30,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?auto=format&fit=crop&q=80&w=800',
    description: 'The world\'s largest selling biscuit brand. Tea\'s best friend.',
    color: '#b45309',
    unit: '200 g'
  },
  {
    id: '16',
    name: 'Coca-Cola Soft Drink',
    price: 85,
    mrp: 95,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&q=80&w=800',
    description: 'Refreshing carbonated beverage. Best served chilled.',
    color: '#ef4444',
    unit: '2.25 L'
  },
  {
    id: '17',
    name: 'Nescafe Classic Coffee',
    price: 165,
    mrp: 180,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
    description: 'Rich and aromatic instant coffee granules.',
    color: '#451a03',
    unit: '50 g'
  },
  {
    id: '18',
    name: 'Surf Excel Easy Wash',
    price: 215,
    mrp: 240,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1626806819282-2c1dfbd1a5e6?auto=format&fit=crop&q=80&w=800',
    description: 'Superfine powder that dissolves easily and removes tough stains.',
    color: '#3b82f6',
    unit: '1 kg'
  },
  {
    id: '19',
    name: 'Fresh Royal Gala Apples',
    name_hi: 'ताजे रॉयल गाला सेब',
    name_gu: 'તાજા રોયલ ગાલા સફરજન',
    price: 180,
    mrp: 220,
    category: 'Fruits & Veggies',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6bcd6?auto=format&fit=crop&q=80&w=800',
    description: 'Sweet and crunchy apples imported from the best orchards.',
    description_hi: 'सबसे अच्छे बागों से आयातित मीठे और कुरकुरे सेब।',
    description_gu: 'શ્રેષ્ઠ બગીચાઓમાંથી આયાત કરેલા મીઠા અને કરકરા સફરજન.',
    color: '#ef4444',
    unit: '1 kg'
  },
  {
    id: '20',
    name: 'Organic Cavendish Banana',
    name_hi: 'जैविक कैवेंडिश केला',
    name_gu: 'ઓર્ગેનિક કેવેન્ડિશ કેળા',
    price: 60,
    mrp: 75,
    category: 'Fruits & Veggies',
    image: 'https://images.unsplash.com/photo-1571771894821-ad996211fdf4?auto=format&fit=crop&q=80&w=800',
    description: 'Partially ripe bananas, rich in potassium and fiber.',
    description_hi: 'आंशिक रूप से पके हुए केले, पोटेशियम और फाइबर से भरपूर।',
    description_gu: 'પાર્શિયલ પાકેલા કેળા, પોટેશિયમ અને ફાઇબરથી ભરપૂર.',
    color: '#facc15',
    unit: '1 kg'
  },
  {
    id: '21',
    name: 'Madhur Pure & Hygienic Sugar',
    name_hi: 'मधुर शुद्ध और स्वच्छ चीनी',
    name_gu: 'મધુર શુદ્ધ અને સ્વચ્છ ખાંડ',
    price: 52,
    mrp: 55,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&q=80&w=800',
    description: 'Sulphur-free, pure white crystalline sugar.',
    description_hi: 'सल्फर मुक्त, शुद्ध सफेद क्रिस्टलीय चीनी।',
    description_gu: 'સલ્ફર મુક્ત, શુદ્ધ સફેદ સ્ફટિકીય ખાંડ.',
    color: '#ffffff',
    unit: '1 kg'
  },
  {
    id: '22',
    name: 'Tata Sampann Toor Dal',
    name_hi: 'टाटा संपन्न तूर दाल',
    name_gu: 'ટાટા સંપન્ન તુવેર દાળ',
    price: 175,
    mrp: 190,
    category: 'Grocery',
    image: 'https://images.unsplash.com/photo-1585994192730-981844a7543d?auto=format&fit=crop&q=80&w=800',
    description: 'Unpolished toor dal, rich in protein and authentic taste.',
    description_hi: 'बिना पॉलिश की हुई तूर दाल, प्रोटीन से भरपूर और असली स्वाद।',
    description_gu: 'અનપોલિશ્ડ તુવેર દાળ, પ્રોટીનથી ભરપૂર અને અસલી સ્વાદ.',
    color: '#eab308',
    unit: '1 kg'
  },
  {
    id: '23',
    name: 'Colgate MaxFresh Toothpaste',
    name_hi: 'कोलगेट मैक्सफ्रेश टूथपेस्ट',
    name_gu: 'કોલગેટ મેક્સફ્રેશ ટૂથપેસ્ટ',
    price: 195,
    mrp: 220,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1559591937-e68fb3305e4d?auto=format&fit=crop&q=80&w=800',
    description: 'Infused with cooling crystals for intense freshness.',
    description_hi: 'तीव्र ताजगी के लिए कूलिंग क्रिस्टल से भरपूर।',
    description_gu: 'તીવ્ર તાજગી માટે કૂલિંગ ક્રિસ્ટલ્સ સાથે.',
    color: '#3b82f6',
    unit: '150 g x 2'
  },
  {
    id: '24',
    name: 'Dove Cream Beauty Bar Soap',
    name_hi: 'डव क्रीम ब्यूटी बार साबुन',
    name_gu: 'ડવ ક્રીમ બ્યુટી બાર સાબુ',
    price: 345,
    mrp: 380,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&q=80&w=800',
    description: 'Contains 1/4 moisturizing cream for soft, smooth skin.',
    description_hi: 'नरम, चिकनी त्वचा के लिए 1/4 मॉइस्चराइजिंग क्रीम शामिल है।',
    description_gu: 'નરમ, મુલાયમ ત્વચા માટે 1/4 મોઇશ્ચરાઇઝિંગ ક્રીમ ધરાવે છે.',
    color: '#ffffff',
    unit: '125 g x 3'
  },
  {
    id: '25',
    name: 'Lays India\'s Magic Masala',
    name_hi: 'लेज इंडियाज मैजिक मसाला',
    name_gu: 'લેઝ ઈન્ડિયાઝ મેજિક મસાલા',
    price: 48,
    mrp: 50,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1566478431373-7821e9366ef7?auto=format&fit=crop&q=80&w=800',
    description: 'Crunchy potato chips flavored with spicy Indian masalas.',
    description_hi: 'मसालेदार भारतीय मसालों के साथ कुरकुरे आलू के चिप्स।',
    description_gu: 'તીખા ભારતીય મસાલાઓ સાથે ક્રિસ્પી બટાકાની ચિપ્સ.',
    color: '#1e3a8a',
    unit: '90 g'
  },
  {
    id: '26',
    name: 'Bikano Navratna Mix',
    name_hi: 'बीकानो नवरत्न मिक्स',
    name_gu: 'બીકાનો નવરત્ન મિક્સ',
    price: 75,
    mrp: 85,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1627914602044-d982a9d9483b?auto=format&fit=crop&q=80&w=800',
    description: 'A savory blend of lentils, nuts, and spices.',
    description_hi: 'दालों, मेवों और मसालों का एक नमकीन मिश्रण।',
    description_gu: 'દાળ, નટ અને મસાલાઓનું સ્વાદિષ્ટ મિશ્રણ.',
    color: '#d97706',
    unit: '200 g'
  },
  {
    id: '27',
    name: 'Vim Dishwash Liquid Gel',
    name_hi: 'विम डिशवॉश लिक्विड जेल',
    name_gu: 'વિમ ડિશવોશ લિક્વિડ જેલ',
    price: 155,
    mrp: 175,
    category: 'Household',
    image: 'https://images.unsplash.com/photo-1584622781564-1d9876a13d1e?auto=format&fit=crop&q=80&w=800',
    description: 'Power of 100 lemons. Cleans tough grease effortlessly.',
    description_hi: '100 नींबू की शक्ति। सख्त ग्रीस को आसानी से साफ करता है।',
    description_gu: '100 લીંબુની શક્તિ. કઠણ ચીકાશને વિના પ્રયાસે સાફ કરે છે.',
    color: '#fbbf24',
    unit: '750 ml'
  },
  {
    id: '28',
    name: 'Harpic Power Plus',
    name_hi: 'हार्पिक पावर प्लस',
    name_gu: 'હારપિક પાવર પ્લસ',
    price: 185,
    mrp: 210,
    category: 'Household',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800',
    description: '10x better stain removal for a sparkling clean toilet.',
    description_hi: 'चमकते हुए साफ टॉयलेट के लिए 10 गुना बेहतर दाग हटाना।',
    description_gu: 'ચળકતા શૌચાલય માટે 10 ગણા વધુ સારી ડાઘ સફાઈ.',
    color: '#1e3a8a',
    unit: '1 L'
  },
  {
    id: '29',
    name: 'Paper Boat Aam Panna',
    name_hi: 'पेपर बोट आम पन्ना',
    name_gu: 'પેપર બોટ આમ પન્ના',
    price: 35,
    mrp: 40,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1544381905-06490ffaba8f?auto=format&fit=crop&q=80&w=800',
    description: 'Tangy green mango drink, tastes like childhood.',
    description_hi: 'तीखा हरा आम का ड्रिंक, बचपन जैसा स्वाद।',
    description_gu: 'ખાટું પન્ના, બાળપણની યાદ અપાવે તેવો સ્વાદ.',
    color: '#bef264',
    unit: '250 ml'
  },
  {
    id: '30',
    name: 'Cadbury Dairy Milk Silk',
    name_hi: 'कैडबरी डेयरी मिल्क सिल्क',
    name_gu: 'કેડબરી ડેરી મિલ્ક સિલ્ક',
    price: 160,
    mrp: 175,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=800',
    description: 'Smooth and silky chocolate for an indulgent experience.',
    description_hi: 'एक शानदार अनुभव के लिए चिकनी और रेशमी चॉकलेट।',
    description_gu: 'ભરપૂર આનંદ માટે નરમ અને રેશમી ચોકલેટ.',
    color: '#4c1d95',
    unit: '150 g'
  }
];
